version: "3.8"

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./www:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_USER: camagru_user
      MYSQL_PASSWORD: toor
    volumes:
      # - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 3001:80
    environment:
      PMA_HOST: db
volumes:
  persistent:
